name: Analyze GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo-url:
        description: 'GitHub repository URL to analyze'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run repo analysis
      working-directory: ./backend
      env:
        GITHUB_TOKEN: \$'{{ secrets.GITHUB_TOKEN }}
      run: node index.js \$'{{ github.event.inputs.repo-url }}

    - name: Copy report to frontend
      run: cp ./backend/report.json ./frontend/public/report.json

    - name: Setup frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: \$'{{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
